### ISSUE TITLE
Why use the find module for GTest

### ISSUE THREAD

**Issue by nolange** [mpusz/new-project-template#1]
Hello,

thanks for saving me alot time with this template. I have a question however regarding `find_package(GTest MODULE REQUIRED)`.
My philosophy would be to prefer the config files installed by GTest itself, as finding modules is somewhat more complicated than configs in crossbuilds (you can direct CMake with a single Variable GTest_DIR to the CONFIG installation, but have to adjust paths for headers+libs for MODULES [relevant issue](https://github.com/conan-io/conan/issues/4967)).

Is there some disadvantage I am missing?

**Comment by mpusz** [comment]
Hi,

I am glad it helped you. :-)

Regarding your MODULE vs CONFIG question the answer is that if I remember correctly gtest had some compilation issues on some compilers and bincrafters provided custom Find<PackageName>.cmake that was fixing that issue.

Anyway, with time and experience I am more and more biased that find_package does not scale and do not support some scenarios that is why I plan to drop find_package support soon and switch to conan-only usage.

**Comment by nolange** [comment]
> Regarding your MODULE vs CONFIG question the answer is that if I remember correctly gtest had some compilation issues on some compilers and bincrafters provided custom Find.cmake that was fixing that issue.

The Find-Modules have unusual target-names (not what a native CMake build would produce).

> Anyway, with time and experience I am more and more biased that find_package does not scale and do not support some scenarios that is why I plan to drop find_package support soon and switch to conan-only usage.

You mean using the `CONAN_PKG::` targets, would that work if you for example need Qt5 with its [macros and preprocessor schenanigans](https://doc.qt.io/qt-5/cmake-manual.html)?
That would probably be highly invasive to a project... I am still trying to leave Conan optional for now.

Btw. is that really a problem with CONFIG Mode packages, or just (Find-) MODULES?
The config ones should just create the targets and not poke around much.

**Comment by mpusz** [comment]
`FindGTest.cmake` is distributed with every CMake installation. Bincrafters also provide custom `FindGTest.cmake` in their Conan package. I chose to use MODULE instead of CONFIG because Bincrafters  did not perform cmake install step and with that, the package was missing `GTestConfig.cmake` file :-( That is why I decided to go with MODULE for that specific package at that time.

Now, I checked that package gtest 1.8.1 works correctly and includes install step so I am updating the project. It should appear with a lot of new handy stuff soon :-)
